name: ci
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: cloud_a02_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
    env:
      NODE_ENV: test
      JWT_SECRET: ci_secret
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/cloud_a02_test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/cloud_a02_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install deps
        run: npm ci
      - name: Init schema
        run: psql "$TEST_DATABASE_URL" -f sql/schema.sql
      - name: Run tests
        run: npm run test:ci
